apiVersion: v1
kind: ConfigMap
metadata:
  name: caretta-prometheus-config-volume
  namespace: {{.Release.Namespace}}
data:
  prometheus.yml: |
    scrape_configs:
      - job_name:       'caretta'
        metrics_path: /metrics
        scrape_interval: 5s
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - caretta-test
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            separator: ;
            regex: caretta
            replacement: $1
            action: keep
          - action: labelmap
            regex: __meta_kubrnetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: caretta_pod
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: caretta_node
