{{ if .Values.persistentStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: caretta-vm-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: "caretta-victoria"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
{{ end }}
