apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "caretta.name" . }}-podmonitor
  namespace: {{ .Values.podMonitor.namespace | default .Release.Namespace }}
  {{- with .Values.podMonitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- with .Values.podMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.podMonitor.namespace }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      app: caretta
      {{- include "caretta.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - honorLabels: {{ .Values.podMonitor.honorLabels }}
    port: prom-metrics
    {{- with .Values.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    scheme: http
    {{- with .Values.podMonitor.endpointAdditionalProperties }}
      {{- toYaml . | nindent 4 }}
    {{- end }}