name: subcharts-images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'chart/charts/**'
      - '.github/workflows/subcharts.yaml'

defaults:
 run:
  working-directory: chart/charts

jobs:
  subchart-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push Grafana Image
        run: |
          IMAGE_TAG=$(helm show chart grafana* | yq e '.appVersion' -)
          docker buildx imagetools create grafana/grafana:${IMAGE_TAG} --tag quay.io/groundcover/grafana:${IMAGE_TAG}
      -
        name: Push Victoria-Metrics Image
        run: |
          IMAGE_TAG=v$(helm show chart victoria-metrics* | yq e '.appVersion' -)
          docker buildx imagetools create victoriametrics/victoria-metrics:${IMAGE_TAG}  --tag quay.io/groundcover/victoria-metrics:${IMAGE_TAG}
